main: teik.ers.bukkit.EpicReports
name: EpicReports
version: 4.0.0
author: teik

commands:
  report:
    description: Report players
  epicreports:
    description: Admin commands

Permissions:
  EasyReports.Admin:
    description: Send op commands
    default: op
  EasyReports.User:
    description: Send user commands
    default: true